services:
    - type: pserv
      name: security-cats-mysql  # Match your service name
      plan: starter  # Free tier
      env: docker
      dockerfilePath: ./Dockerfile
      autoDeploy: false
      disk:
        name: mysql-data
        mountPath: /var/lib/mysql
        sizeGB: 1  # Reduced to minimize cost ($0.25/month)
      envVars:
      - fromGroup: mysql

    envVarGroups:
    - name: mysql
      envVars:
      - key: MYSQL_DATABASE
        value: securitycats  # Match Flask app
      - key: MYSQL_USER
        value: app_user
      - key: MYSQL_PASSWORD
        generateValue: true
      - key: MYSQL_ROOT_PASSWORD
        generateValue: true